version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.5.1-node

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile" }}

      - run:
          name: run tests
          command: |
            bundle exec rake

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
