version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - middleman-inline_svg-bundle-v1-{{ checksum "middleman-inline_svg.gemspec" }}
            - middleman-inline_svg-bundle-v1-
      - run:
          name: Run Bundler
          command: bundle install --path vendor/bundle
      - save_cache:
          key: middleman-inline_svg-bundle-v1-{{ checksum "middleman-inline_svg.gemspec" }}
          paths:
            - ./vendor/bundle
      - run:
          name: Run tests
          command: bundle exec rake
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
